### ISSUE TITLE
120 video_tutorial.html

### ISSUE THREAD

**Issue by QiuMing** [jhipster-cn/jhipster-document#74]

**Comment by 514840279** [comment]
这个酱油 我打了
虽然 不太懂 ，

**Comment by 514840279** [comment]
有些 翻译 不明白

**Comment by 514840279** [comment]
视频 教程


JHipster 博客 演示

这是一个拥有20分钟的视屏,它向我们展示了如何使用提供的工具（Maven，Gulp）创建一个JHipster的应用, 使用实体生成模块去创建 几个带有关联性的实体, 并在云产品上部署最终的结果.

发布者： Matt Raible (@mraible)

发布于： 2016年2月7日

其他 JHipster 视屏


2016 JHipster 发生那些变化?

2016年 JHipster的新特性是构建微服务.

发布者： Julien Dubois (@juliendubois)

发布于： 2016年6月16日


创建一个微服务应用的方法

7分钟的演示向我们展示了如何快速创建一个关联的应用，使用实体生成模块在两个项目中运行jhipster实体注册。你需要有YouTube的评论能够看到指示(这个视频没有声音，你就边做边看吧).

发布者： Victor Gil (@baskeboler)

发布于： 2016年5月21日


JHipster 3.0 新变化

这是一个jhipster 3介绍法国Devoxx的视频。

发布者： Matt Raible (@mraible)

发布于： 2016年5月9日


(in French) What's new for JHipster in 2016?

JHipster 2016的新特性 , 焦点在构建一个微服务. 提示, 这个视频是法语的!

发布者： Julien Dubois (@juliendubois)

发布于： 2016年5月9日


JHipster 3.0

这是一个JHipster 3.0视频的教程介绍新加坡的Spring用户组.

发布者： Deepu KS (@deepu105)

发布于： 2016年2月16日

**Comment by deepu105** [comment]
Wow :)

**Comment by baskeboler** [comment]
:)

**Comment by QiuMing** [comment]
好像 被开发组成员 注意到了，@514840279   帮你校验了好了，== ，翻译的时候不要 把 html  文件去了，在原有文件的基础上翻译就好。https://github.com/jhipster-cn/jhipster-document/blob/v3.5.0_cn/pages/video_tutorial.html ，你可以看下。
